### ISSUE TITLE
[breaking][autofix] stylus/indentation rule auto fix removes lines when using multi line properties

### ISSUE THREAD

**Issue by Cactusbone** [stylus/stylelint-stylus#17]
when using --fix with stylus/indentation rule enabled, some lines are removed from stylus files.

example from https://stackoverflow.com/a/48514878/422995

```
div
    box-shadow \
    0 0 0 black \
    1 0 0 black \
    0 0 1 black
    color: white
```

becomes 

```
div
    box-shadow \
    color: white
```
with 3 lines being removed

**Comment by ota-meshi** [comment]
Reproduction:

https://stylus.github.io/stylelint-stylus/playground/#eJxtjd0OgjAMRl9l6TVE8ZJXsV7AVmFxtAbGjyG8uxtTY6LdTXO+860raDEEJRg7IaswtSz50FZGZoWY0HF/tav07cOKPyySIrEEtDjpSzW31hNk4RRfbROOrTFGuLuxsTwglOqMMPiHI2fZ53EbA75kyaPFE5uXt3/8ax960tJ1wSODEK13ux8d7d31uxsaNrjsK2+FY3yK8Ya8wfYEKtdYDA==
